#!/usr/bin/env bash
# do some lookup

#SUB = $2


do_lookup_ip () {
	if [ $# -gt 1 ] 
	then
		just_record=$(dig $SUB.$DOMAIN | grep -A 1 "ANSWER SECTION"| awk '{print $4}')
		just_ip=$(dig $SUB.$DOMAIN | grep -A 1 "ANSWER SECTION" | awk '{print $5}') 
		echo The subdomain "$SUB" is a $just_record record and points to $just_ip
	else
		for str in ${collection[@]}
	       	do
			just_record=$(dig $str.$DOMAIN | grep -A 1 "ANSWER SECTION"| awk '{print $4}')
                	just_ip=$(dig $str.$DOMAIN | grep -A 1 "ANSWER SECTION" | awk '{print $5}')
                	echo The subdomain "$str" is a $just_record record and points to $just_ip
		done
	fi
}

DOMAIN=$1
SUB=$2
collection=("www" "lb-01" "web-01" "web-02")


do_lookup_ip $1 $2
